# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: repeatreg
  - /task: regression
  - /optimizer: adamw
  - /scheduler: constant

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: max

trainer:
  max_epochs: 400

encoder: linear

decoder:
  _name_: sequence
  mode: last

